[package]
name = "encurta"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
dotenvy = "0.15.7"
libsql = "0.9.11"
limbo = "0.0.22"
serde = { version = "1.0.219", features = ["derive"] }
sha256 = "1.6.0"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
